import { TravelDestination, LocalActivity, BudgetLevel, TravelCategory } from './types';

export const DESTINATIONS: TravelDestination[] = [
  // Weekend trips
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    tagline: 'City of Light, always magical',
    description: 'From the Eiffel Tower to hidden bistros, Paris rewards even a quick visit.',
    duration: '2–3 days',
    budgetLevel: 'mid',
    category: 'city',
    emoji: '🗼',
    bestFor: ['couples', 'culture', 'food'],
    regions: ['europe', 'turkey'],
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    tagline: 'Canals, cycling, and culture',
    description: 'World-class museums, scenic canals, and a vibrant food scene.',
    duration: '2–3 days',
    budgetLevel: 'mid',
    category: 'city',
    emoji: '🚲',
    bestFor: ['solo', 'couples', 'friends'],
    regions: ['europe'],
  },
  {
    id: 'prague',
    name: 'Prague',
    country: 'Czech Republic',
    tagline: 'Medieval charm at its finest',
    description: 'Gothic architecture, fairy-tale streets, and affordable luxury.',
    duration: '3–4 days',
    budgetLevel: 'low',
    category: 'city',
    emoji: '🏰',
    bestFor: ['couples', 'solo', 'history'],
    regions: ['europe', 'turkey'],
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    tagline: 'Sun, Gaudí, and tapas',
    description: 'Gaudi\'s masterpieces, golden beaches, and legendary nightlife.',
    duration: '3–5 days',
    budgetLevel: 'mid',
    category: 'city',
    emoji: '🌊',
    bestFor: ['families', 'couples', 'beach'],
    regions: ['europe', 'turkey'],
  },
  {
    id: 'lisbon',
    name: 'Lisbon',
    country: 'Portugal',
    tagline: 'Fado, hills, and golden light',
    description: 'One of Europe\'s most charming capitals — warm, affordable, and deeply soulful.',
    duration: '3–4 days',
    budgetLevel: 'low',
    category: 'city',
    emoji: '🌅',
    bestFor: ['solo', 'couples', 'culture'],
    regions: ['europe'],
  },
  // Nature escapes
  {
    id: 'dolomites',
    name: 'Dolomites',
    country: 'Italy',
    tagline: 'Dramatic peaks and alpine tranquility',
    description: 'UNESCO World Heritage mountain range with stunning hikes and cozy rifugios.',
    duration: '3–5 days',
    budgetLevel: 'mid',
    category: 'nature',
    emoji: '⛰️',
    bestFor: ['nature', 'hiking', 'couples'],
    regions: ['europe'],
  },
  {
    id: 'fjords',
    name: 'Norwegian Fjords',
    country: 'Norway',
    tagline: 'Nature\'s most dramatic canvas',
    description: 'Towering cliffs, mirror-like water, and absolute serenity.',
    duration: '4–7 days',
    budgetLevel: 'high',
    category: 'nature',
    emoji: '🏔️',
    bestFor: ['nature', 'adventure', 'couples'],
    regions: ['europe'],
  },
  {
    id: 'cappadocia',
    name: 'Cappadocia',
    country: 'Turkey',
    tagline: 'Hot air balloons over fairy chimneys',
    description: 'Surreal volcanic landscape with cave hotels, underground cities, and sunrise balloon rides.',
    duration: '3–4 days',
    budgetLevel: 'mid',
    category: 'nature',
    emoji: '🎈',
    bestFor: ['couples', 'adventure', 'families'],
    regions: ['europe', 'turkey', 'asia'],
  },
  {
    id: 'swiss-alps',
    name: 'Swiss Alps',
    country: 'Switzerland',
    tagline: 'Pristine peaks and picture-perfect villages',
    description: 'Interlaken, Zermatt, and Grindelwald offer world-class scenery and skiing.',
    duration: '4–7 days',
    budgetLevel: 'high',
    category: 'nature',
    emoji: '🏞️',
    bestFor: ['families', 'adventure', 'couples'],
    regions: ['europe'],
  },
  {
    id: 'black-sea',
    name: 'Black Sea Coast',
    country: 'Turkey',
    tagline: 'Lush mountains meet the sea',
    description: 'Green valleys, tea gardens, and a coastline less traveled.',
    duration: '3–5 days',
    budgetLevel: 'low',
    category: 'nature',
    emoji: '🌿',
    bestFor: ['nature', 'families', 'relaxation'],
    regions: ['turkey'],
  },
  // International travel
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    tagline: 'Where ancient meets hypermodern',
    description: 'A city of contrasts — serene temples beside neon-lit streets and extraordinary food.',
    duration: '7–10 days',
    budgetLevel: 'mid',
    category: 'international',
    emoji: '⛩️',
    bestFor: ['solo', 'culture', 'food'],
    regions: ['europe', 'americas', 'turkey', 'asia'],
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    tagline: 'Spiritual beauty and tropical bliss',
    description: 'Rice terraces, surf breaks, and spiritual retreats make Bali endlessly restorative.',
    duration: '7–14 days',
    budgetLevel: 'low',
    category: 'international',
    emoji: '🌴',
    bestFor: ['solo', 'couples', 'wellness'],
    regions: ['europe', 'americas', 'turkey', 'asia'],
  },
  {
    id: 'new-york',
    name: 'New York',
    country: 'USA',
    tagline: 'The city that never sleeps',
    description: 'World-class museums, iconic food scenes, and neighborhoods to explore for weeks.',
    duration: '5–7 days',
    budgetLevel: 'high',
    category: 'international',
    emoji: '🗽',
    bestFor: ['culture', 'food', 'couples', 'solo'],
    regions: ['europe', 'turkey'],
  },
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Morocco',
    tagline: 'Sensory overload in the best way',
    description: 'Labyrinthine medinas, spice-scented souks, and rooftop mint tea.',
    duration: '3–5 days',
    budgetLevel: 'low',
    category: 'international',
    emoji: '🕌',
    bestFor: ['solo', 'couples', 'culture'],
    regions: ['europe', 'turkey'],
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    country: 'Turkey',
    tagline: 'Where continents collide',
    description: 'Hagia Sophia, the Bosphorus, and the world\'s best baklava in one city.',
    duration: '3–5 days',
    budgetLevel: 'low',
    category: 'city',
    emoji: '🌙',
    bestFor: ['history', 'food', 'couples'],
    regions: ['europe', 'americas', 'asia'],
  },
  {
    id: 'costa-rica',
    name: 'Costa Rica',
    country: 'Costa Rica',
    tagline: 'Pura vida — rainforests and volcanoes',
    description: 'Biodiversity hotspot with ziplines, sloths, and stunning Pacific beaches.',
    duration: '7–14 days',
    budgetLevel: 'mid',
    category: 'international',
    emoji: '🦥',
    bestFor: ['adventure', 'families', 'nature'],
    regions: ['americas'],
  },
  // US destinations for Americas region
  {
    id: 'grand-canyon',
    name: 'Grand Canyon',
    country: 'USA',
    tagline: 'One of Earth\'s greatest wonders',
    description: 'Hike the rim, raft the Colorado, or simply stand in awe of nature\'s masterpiece.',
    duration: '2–4 days',
    budgetLevel: 'mid',
    category: 'nature',
    emoji: '🏜️',
    bestFor: ['families', 'nature', 'adventure'],
    regions: ['americas'],
  },
  {
    id: 'national-parks',
    name: 'Yellowstone & Grand Teton',
    country: 'USA',
    tagline: 'America\'s wilderness at its best',
    description: 'Geysers, bison herds, and mountain peaks — a road trip to remember.',
    duration: '5–7 days',
    budgetLevel: 'mid',
    category: 'nature',
    emoji: '🌋',
    bestFor: ['families', 'nature', 'adventure'],
    regions: ['americas'],
  },
];

export const LOCAL_ACTIVITIES: LocalActivity[] = [
  { id: 'sunset-walk', name: 'Sunset nature walk', category: 'outdoor', duration: '1–2 hrs', emoji: '🌄', bestTime: 'after-work' },
  { id: 'local-market', name: 'Local farmers market', category: 'food', duration: '1 hr', emoji: '🥕', bestTime: 'weekend' },
  { id: 'gallery-visit', name: 'Gallery or museum visit', category: 'culture', duration: '2 hrs', emoji: '🎨', bestTime: 'evening' },
  { id: 'yoga-class', name: 'Outdoor yoga class', category: 'wellness', duration: '1 hr', emoji: '🧘', bestTime: 'after-work' },
  { id: 'rooftop-bar', name: 'Rooftop bar with a view', category: 'social', duration: '2 hrs', emoji: '🍹', bestTime: 'evening' },
  { id: 'cycling', name: 'Evening cycling route', category: 'outdoor', duration: '1–2 hrs', emoji: '🚴', bestTime: 'after-work' },
  { id: 'night-market', name: 'Night food market', category: 'food', duration: '2 hrs', emoji: '🏮', bestTime: 'evening' },
  { id: 'kayak', name: 'Kayaking on a local river', category: 'outdoor', duration: '2–3 hrs', emoji: '🚣', bestTime: 'weekend' },
  { id: 'cooking', name: 'Local cuisine cooking class', category: 'food', duration: '3 hrs', emoji: '👨‍🍳', bestTime: 'weekend' },
  { id: 'stargazing', name: 'Stargazing spot', category: 'outdoor', duration: '1–2 hrs', emoji: '✨', bestTime: 'evening' },
];

export function filterDestinations(
  destinations: TravelDestination[],
  region: string,
  budget: BudgetLevel,
  category?: TravelCategory,
  durationDays?: number
): TravelDestination[] {
  const budgetOrder: BudgetLevel[] = ['low', 'mid', 'high'];
  const budgetIndex = budgetOrder.indexOf(budget);

  return destinations.filter(d => {
    const regionMatch = d.regions.includes(region);
    const budgetMatch = budgetOrder.indexOf(d.budgetLevel) <= budgetIndex;
    const categoryMatch = !category || d.category === category;

    // Duration filter: if durationDays provided, only show appropriate destinations
    let durationMatch = true;
    if (durationDays !== undefined) {
      if (durationDays <= 3 && d.category === 'international') durationMatch = false;
      if (durationDays >= 7 && d.category === 'weekend') durationMatch = false;
    }

    return regionMatch && budgetMatch && categoryMatch && durationMatch;
  });
}
